// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "N10+Yangyu"
#define SECRET_PASS "1791234yangyu*"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a19613o2uxxm5b-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUWkQEqvWysWDtvLc9raTtA43ZfIAwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMTIwOTAwNDAw
MloXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABFRMQ2v/oUjojj6TAbNTrutzhhMpX3MrgoDm
gUoGUHvDQ5pX1GziL8YDCax9OQiJuDew+2T3VGtPLrS4WbAOlq6jYDBeMB8GA1Ud
IwQYMBaAFFLUJYwzsPACHKFvFK/Lgi1BVSB3MB0GA1UdDgQWBBSuXjkFlSqLRmK/
9h0TRzuOVPvglDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAkTMvP70PPwkDMihZQfx+IneHGqGV+laSwagLnSsoRgAdwsEp
X/xJLQ9sBqQ5Ruk8dJ5CcAdMWEfxBFcmlS4Be06HuR4u+vi8ac+AKpAYagHg0y6o
v8YDqVB6rjGosJ4RQKJ5QQvZgRMthhPaME+/Dd/xUeXxp0TvQt7upLixqoguKc8m
0fHCgPYBlrakNf/snZBs9rFaweAqWBFQg1piyXjPw7Ggp81550eHwlxQL/mWJ42S
rW2oDOtqdk6YjU9F9WLMKD7KEnsy1JzWeqGTeUBTJZSiUTWftTN2BqASZohqCIg+
7dlj0zgSUh/KMuBI+hSYzy/aj3zS1anIIDLgAg==
-----END CERTIFICATE-----
)";
